AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  appflow-compliance

  Sample SAM Template for appflow-compliance
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  AppFlowComplianceFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Policies:
        - DynamoDBWritePolicy:
            TableName: "appflow-compliance-lock"
        - DynamoDBReadPolicy:
            TableName: "appflow-compliance-lock"            
        - Statement:
          - Sid: AppFlowFullPermission
            Effect: Allow
            Action:
            - appflow:*
            Resource: '*'
         
      Events:
        CloudWatchEvent1:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail-type:
                - AWS API Call via CloudTrail
              source:
                - aws.appflow
              detail:
                eventSource:
                  - appflow.amazonaws.com            

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  # HelloWorldApi:
  #   Description: "API Gateway endpoint URL for Prod stage for Hello World function"
  #   Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  AppFlowComplianceFunction:
    Description: "AppFlow Compliance Function ARN"
    Value: !GetAtt AppFlowComplianceFunction.Arn
  AppFlowComplianceFunctionIamRole:
    Description: "Implicit IAM Role created for AppFlow Compliance function"
    Value: !GetAtt AppFlowComplianceFunctionRole.Arn
